apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 3306
  selector:
    app: {{ .Release.Name }}-mysql
