replicaCount: 1

image:
  imageRegistry: "registry-2.yunna.net"
  repository: filebrowser/filebrowser
  tag: "v2.31.2"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  externalPort: 80

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

persistence:
  enabled: true
  storageClass: "local"
  accessMode: ReadWriteOnce
  srvSize: 10Gi
  configSize: 1Gi

env:
  env1: 
    name: FB_PORT
    value: "80"
  env2:
    name: FB_ROOT
    value: "/srv"
  env3:
    name: FB_DATABASE
    value: "/var/config/database.db"
  env4:
    name: FB_LOG
    value: "stdout"

config:
  filebrowserJson: |
    {
      "port": 80,
      "baseURL": "",
      "address": "",
      "log": "stdout",
      "database": "/var/config/database.db",
      "root": "/srv"
    }
  databaseDb: ""